content:
  - name: features
    label: Features
    type: collection
    path: content/features
    format: json

    fields:
      - name: title
        label: Feature Title
        type: string

      - name: description
        label: Feature Description
        type: text