content:
  - name: features
    label: Features
    path: content/homepage/features
    type: collection
    fields:
      - {name: title, label: Title, type: string, required: true}
      - {name: description, label: Title, type: rich-text, required: true}