content:
  - name: features
    label: Features
    path: content/features.json
    type: file
    format: json

    fields:
      - name: features
        label: Features
        type: object
        fields:
          - name: title
            label: Feature Title
            type: string

          - name: description
            label: Feature Description
            type: text