content:
  - name: features
    label: Features
    type: collection
    path: content/homepage/features
    fields:
      - { name: title, label: Title, type: string }
      - { name: description, label: Description, type: string }