content:
  - name: features
    label: Features
    type: collection
    path: content/homepage/features
    format: json

    fields:
      - { name: title, type: string }
      - { name: description, type: string }